global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  origin_x: -5.0 # only works for static map
  origin_y: -5.0 # only works for static map
